<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search bookings
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["bookings/new", "Create bookings"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "bookings/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBookingDate" class="col-sm-2 control-label">Booking Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["bookingDate", "type" => "date", "class" => "form-control", "id" => "fieldBookingDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStartTime" class="col-sm-2 control-label">Start Of Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["startTime", "size" => 30, "class" => "form-control", "id" => "fieldStartTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEndTime" class="col-sm-2 control-label">End Of Time</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["endTime", "size" => 30, "class" => "form-control", "id" => "fieldEndTime"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMemberId" class="col-sm-2 control-label">Member</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["memberId", "type" => "number", "class" => "form-control", "id" => "fieldMemberId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCourtId" class="col-sm-2 control-label">Court</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["courtId", "type" => "number", "class" => "form-control", "id" => "fieldCourtId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFee" class="col-sm-2 control-label">Fee</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fee", "type" => "number", "class" => "form-control", "id" => "fieldFee"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
