<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<?php
    $this->assets->outputCss("rating");
    $this->assets->outputJs("rating");
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["courts/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["courts/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Surface</th>
            <th>Floodlights</th>
            <th>Indoor</th>
            <th>Average Rating</th>
            <th>Star Rating</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $court): ?>
            <tr>
                <td><?php echo $court->getId() ?></td>
            <td><?php echo $court->getSurface() ?></td>
            <td><?php echo $court->getFloodlights() ?></td>
            <td><?php echo $court->getIndoor() ?></td>

            <td><?php $avgRating = $court->getAverageRating(); ?>
                <?php echo $this->tag->linkTo(["Courtrating/showRatings/" . $court->getId(), "$avgRating"]); ?></td>

            <td><input id="fieldRating" name="rating" value="<?php echo $court->getAverageRating() ?>"
                type="text" class="rating rating-loading" data-min=0 data-max=5 data-step=1 data-size="sm" data-display-only="true"></td>
            <td><?php echo $court->getIndoor() ?></td>

                <td><?php echo $this->tag->linkTo(["courts/edit/" . $court->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["courtrating/new/" . $court->getId(), "Rate"]); ?></td>
                <td><?php echo $this->tag->linkTo(["courts/delete/" . $court->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("courts/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("courts/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("courts/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("courts/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>