<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search membershiptype
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["membershiptype/new", "Create membershiptype"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "membershiptype/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldMembershiptype" class="col-sm-2 control-label">MembershipType</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["membershipType", "size" => 30, "class" => "form-control", "id" => "fieldMembershiptype"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCourthourlyfee" class="col-sm-2 control-label">CourtHourlyFee</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["courtHourlyFee", "type" => "number", "class" => "form-control", "id" => "fieldCourthourlyfee"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
