<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Members", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit Members
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Members/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMemberType" class="col-sm-2 control-label">Member Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["memberType", "size" => 30, "class" => "form-control", "id" => "fieldMemberType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateOfBirth" class="col-sm-2 control-label">Date Of Birth</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["dateOfBirth", "type" => "date", "class" => "form-control", "id" => "fieldDateOfBirth"]) ?>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Photos</label>
    <div class="col-sm-10" style="padding=top: 0px;padding-bottom:12px; padding-left:5px; padding-right:2px;">
        <div id="thisCarousel" class="carousel slide" data-ride="carousel">

            <!--  Images  -->
            <div class="carousel-inner" role="listbox">
                <?php $i=0;foreach ($memberImages as $memberImage) : ?>
                    <div style="padding-bottom:20px" class="item <?php if ($i++==0)echo 'active'?>">
                        <img src="data:image/jpeg;base64, <?php echo $memberImage->getImageFile() ?>" style="width:45%;height:350px;" class="img-responsive center-block">
                        <?php echo "<br>";
                        echo "<br>";
                        ?>
                        <div class="carousel-caption" style="padding:0;top:auto;bottom:0;color: #000000">
                            <h2><?php echo $memberImage->getDescription() ?></h2>
                        </div>

                    </div>
                <?php endforeach; ?>
            </div>

            <!--  controls  -->
            <a class="left carousel-control" href="#thisCarousel" data-slide="prev" style="background-image:none;color:black;">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#thisCarousel" data-slide="next" style="background-image:none;color:black;">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
