<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Members", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Members
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Members/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
            "enctype" => "multipart/form-data"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMemberType" class="col-sm-2 control-label">Member Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["memberType", "size" => 30, "class" => "form-control", "id" => "fieldMemberType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateOfBirth" class="col-sm-2 control-label">Date Of Birth</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["dateOfBirth", "type" => "date", "class" => "form-control", "id" => "fieldDateOfBirth"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Update your Image</label>
    <div class="col-sm-10">
    <?php echo $this->tag->fileField(["imageFile", "size" => "date", "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
<div>

</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
